### PR TITLE
Version 3

### PR DESCRIPTION
**Pull request by jlmakes**
I think this package is great. Being able to highlight markup in my build process, saves my end users from having to load and parse highlight.js, and wait for DOM changes every page load.

Seriously cool, I appreciate you putting this out there @johannestroeger.

However, development has virtually frozen, and this package uses a now-unsupported version of Node (0.10). One issue that has come up for me (and @icio #14) is that there is no way to use language classes to explicitly declare what syntax highlighting to use.

_Example:_

screen shot 2017-05-28 at 8 25 27 pm

Automatic highlighting is failing to handle my JavaScript inline comment. (It thinks its an empty regular expression, followed by strings and keywords.)

I'm open to taking a look into #11 and #13 as well, but this pull request is to help breathe some life into this package:

- Drop support below Node 4
- Refactor (ES2015)
- Enforce linting
- Support language classes

_After:_

screen shot 2017-06-02 at 11 03 01 am

I know some of it is opinionated, but please share your thoughts!

### CODE REVIEW

**Comment by jlmakes** [comment]
I assumed it was related to the JSHint rules, but I’ve added it back.

**Comment by johannestroeger** [comment]
thanks. i'll check the rest asap!

**Comment by jlmakes** [comment]
Just let me know if I went too far with changes to code style. I don‘t want my habits to prevent this awesome lib from getting updated.

**Comment by jlmakes** [comment]
Bump

**Comment by jlmakes** [comment]
😅

**Comment by rwwagner90** [comment]
It's been over a year, any chance we could get this merged please?

**Comment by jlmakes** [comment]
Since the original PR, Node 4 has been sunset—so we should at least bump to Node 6.

**Pull request merged**
